# Frames per second to run the patterns at
fps = 60

# Should the websocket server be abled.  Adds about 30% of one core worth of
# CPU load.
ws_server = true

# Run start-up tests when starting the app.  Will hang if there is no GPS
# signal.
do_startup_tests = false

# How often to report to the backend server, in seconds.  Set to 0 to disable
# reporting.
reporter_interval = 5

# Display a single static pattern
static_pattern = "beans"

# LED strip brightness, 0-255
led_brightness = 128

# This is the mapping between LED strip connectors on the PCB and physical LED
# spine positions on the core icosahedron.  Position in the list corresponds
# LED connectors on the PCB (cables numbered 1-12) while value corresponds to
# which icosahedron position is connected to that connector. Icosahedron
# positions are numbered 1-12 inclusive (i.e. 1-based).
led_spine_mapping = [4, 3, 11, 1, 12, 2, 8, 7, 5, 9, 6, 10]